[variables]
NODE_ENV = 'production'

[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmd = 'cd ../.. && npm install -g pnpm && pnpm install --frozen-lockfile'

[phases.build]
cmd = 'cd ../.. && pnpm build:types && cd apps/rncp_PWA_front && pnpm build'

[start]
cmd = 'pnpm preview --host 0.0.0.0 --port $PORT'