[build]
builder = "nixpacks"
buildCommand = "cd ../.. && pnpm install && pnpm build:types && cd apps/rncp_PWA_front && pnpm build"

[deploy]
startCommand = "pnpm preview --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100

[variables]
NODE_ENV = "production"