[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run preview -- --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100

[variables]
NODE_ENV = "production"
# IMPORTANT: Replace with your actual Railway backend URL