[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100

[variables]
NODE_ENV = "production"
# IMPORTANT: Replace with your actual Railway backend URL
VITE_API_URL = "https://ton-api-test.up.railway.app"