[build]
builder = "nixpacks"

[deploy]
# Pour peupler la DB avec des données de test :
# railway run npm run db:seed:prod
startCommand = "npm run build:railway-full && npm run start:railway-full"
healthcheckPath = "/health"
healthcheckTimeout = 100

[variables]
NODE_ENV = "production"
PORT = "3001"
HOST = "0.0.0.0"
JWT_SECRET = "your-super-secret-jwt-key-for-production"
# Variables PostgreSQL - à configurer dans l'interface Railway
# Ces variables seront automatiquement injectées par Railway si le service PostgreSQL est ajouté
# DB_HOST = (sera défini automatiquement par Railway)
# DB_PORT = (sera défini automatiquement par Railway) 
# DB_USER = (sera défini automatiquement par Railway)
# DB_PASSWORD = (sera défini automatiquement par Railway)
# DB_NAME = (sera défini automatiquement par Railway)
# Frontend URL for CORS configuration (optional - regex fallback will catch all Railway URLs)
FRONTEND_URL = "https://front-production-9bbd.up.railway.app"