version: '3.8'

services:
  # Service de monitoring des métriques
  monitoring-collector:
    image: node:20-alpine
    container_name: rncp-monitoring-collector
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./monitoring:/app/monitoring
      - ./logs:/var/log/monitoring
    working_dir: /app/monitoring
    command: node collector.js
    environment:
      - NODE_ENV=production
      - MONITORING_INTERVAL=30000
      - ALERT_WEBHOOK_URL=${ALERT_WEBHOOK_URL:-}
    depends_on:
      - redis
    networks:
      - rncp-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Dashboard de monitoring (optionnel)
  monitoring-dashboard:
    image: nginx:alpine
    container_name: rncp-monitoring-dashboard
    volumes:
      - ./monitoring/dashboard:/usr/share/nginx/html:ro
      - ./monitoring/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    networks:
      - rncp-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Service de log aggregation
  log-aggregator:
    image: fluent/fluentd:v1.16-debian-1
    container_name: rncp-log-aggregator
    volumes:
      - ./monitoring/fluentd:/fluentd/etc:ro
      - ./logs:/var/log/containers:ro
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - rncp-network
    restart: unless-stopped
    environment:
      - FLUENTD_CONF=fluent.conf

networks:
  rncp-network:
    external: true