name: Release Drafter

on:
    push:
        branches:
            - master

permissions:
    contents: read
    pull-requests: read

jobs:
    update_release_draft:
        permissions:
            contents: write
            pull-requests: read
        runs-on: ubuntu-latest
        steps:
            - name: Release Drafter
              uses: release-drafter/release-drafter@v6
              with:
                  config-name: release-drafter.yml
                  disable-autolabeler: false
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
